spring:
  application:
    name: platform-template
  
  profiles:
    active: local
    
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
        format_sql: true
    show-sql: false
    
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  data:
    redis:
      timeout: 3s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      key:
        refresh-token: "platform:auth:refresh:"
      
  cache:
    type: redis
    redis:
      time-to-live: 3600s
      
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
      
server:
  port: 8081

logging:
  level:
    root: INFO
    com.template.platform: INFO
    org.springframework.cache: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

jwt:
  secret: ${JWT_SECRET:9pvGZfR8MNXZAdYgF3fbVxj8j3vEbUjymgnkB0XfOj4=}
  expiration: ${JWT_EXPIRATION:3600000}

# Swagger/OpenAPI 설정
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
  show-actuator: false

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

  data:
    redis:
      host: localhost
      port: 6370
