spring:
  datasource:
    url: jdbc:postgresql://localhost:35432/template_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    
  data:
    redis:
      host: localhost
      port: 6380
      database: 0

# Local 개발환경에서는 더 자세한 로깅
logging:
  level:
    com.template.platform: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cache: DEBUG